[package]
name = "usbipd-rs"
version = "0.4.2"
edition = "2021"
description = "Inspect connected USB hardware with native cross-platform enumeration."
license = "GPL-3.0-only"
repository = "https://github.com/marc47marc47/usbipd-rs"
readme = "README.md"

[dependencies]
anyhow = "1"
nusb = "0.2"
serialport = "4"
ureq = "2"
unicode-width = "0.2"
zip = { version = "0.6", default-features = false, features = ["deflate"] }

[[bin]]
name = "usbipd-rs"
path = "src/bin/usbipd-rs.rs"
